export const FETCHING_QUESTIONS_REQUEST = "FETCHING_QUESTIONS_REQUEST";
export const FETCHING_QUESTIONS_SUCCESS = "FETCHING_QUESTIONS_SUCCESS";
export const FETCHING_QUESTIONS_ERROR = "FETCHING_QUESTIONS_ERROR";
export const INCREMENT_QUESTIONS = "INCREMENT_QUESTIONS";
export const CORRECT_ANSWER = "CORRECT_ANSWER";
export const SHOW_NEXT = "SHOW_NEXT";
export const SET_BUTTON_VALUE = "SET_BUTTON_VALUE"
